name: Create Speedkeeper Package Application for macOS

on:
  push:
    tags:
      - "*release*"

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - name: Checkout the Project
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6
      - name: Install Dependencies
        run: npm install
      - name: Package Application
        run: npm run package
      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          release_name: Speedkeeper ${{ steps.extract_version.outputs.version }}
          draft: ${{ github.ref != 'refs/head/master' }}
          prerelease: ${{ github.ref != 'refs/head/master' }}
          body: |
            Installation instructions:
            1. Download `speedkeeper.app`
            2. Copy it into the `/Applications` folder
            3. If you want it running right away - double click it
            4. If you want it running everytime you log onto the machine ->
              - Go to `System Preferences -> Users & Groups -> Login Items`
              - Click on the `+`
              - Find the `speedkeeper` inside `Application` and click `Add`
      - name: Upload the Application to Release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./speedkeeper-darwin-x64/speedkeeper.app
          asset_name: speedkeeper.app
          asset_content_type: application/octet-stream
